/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gauss;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jonathan
 */
public class Ventana extends javax.swing.JFrame {

    int[][] matriz;
    DefaultTableModel model =new DefaultTableModel();
    
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        n = new javax.swing.JTextField();
        ingresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        calcular = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        n.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        n.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 110, 50));

        ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gauss/INGRESAR2.png"))); // NOI18N
        ingresar.setBorderPainted(false);
        ingresar.setContentAreaFilled(false);
        ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/gauss/INGRESAR2.png"))); // NOI18N
        ingresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gauss/INGRESAR.png"))); // NOI18N
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        jTable1.setBackground(new java.awt.Color(153, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 300, 190));

        calcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gauss/calculadora (1).png"))); // NOI18N
        calcular.setBorderPainted(false);
        calcular.setContentAreaFilled(false);
        calcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calcular.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/gauss/calculadora (1).png"))); // NOI18N
        calcular.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gauss/calculadora.png"))); // NOI18N
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        getContentPane().add(calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 60, 64));

        jTextArea1.setBackground(new java.awt.Color(153, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 330, 190));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setText("Por favor una ves escrito los valores en la tabla presione la tecla arriba o izquierda");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setText("Si la respuesta te salio NaN es Infinito");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, 40));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("RESOLUCION DE SISTEMA DE ECUACIONES POR GAUSS-JORDAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gauss/cropped-gotas-de-agua-en-hd_131.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        try {
        int columnas = Integer.parseInt(n.getText()); 
       int filas = Integer.parseInt(n.getText());
       columnas = columnas + 1;
       model.setColumnCount(columnas);
       model.setRowCount(filas);
       jTable1.setModel(model);
        }catch(Exception e){JOptionPane.showMessageDialog(this, "Ingrese solo numeros enteros","Mensaje de ingreso", 1);}
    }//GEN-LAST:event_ingresarActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        int tamaño = Integer.parseInt(n.getText());
        CEcuaciones ecuacion = new CEcuaciones(Integer.parseInt(n.getText()));
         matriz = new int[tamaño][tamaño + 1];
        try{
        for (int i = 0; i < matriz.length; i++){
            for(int j = 0;j < matriz[0].length; j++){
               matriz[i][j]=Integer.parseInt(String.valueOf(jTable1.getValueAt(i, j)));
            }
        }
        }catch(Exception e){JOptionPane.showMessageDialog(null,"Ingrese bien los datos","Mensaje",1);}
        ecuacion.setEcuacion(matriz);
        ecuacion.OperacionBásica();
       
        ecuacion.Respuestas();
        String e="";
        for (int i = 0; i < ecuacion.ResueltoCaracteres().size(); i++) 
        {
            e+=ecuacion.ResueltoCaracteres().get(i)+"\n";
        }
        e+="Respuestas"+"\n";
        for (int i = 0; i < ecuacion.getRespuestas().size(); i++) 
        {
            e+=ecuacion.getRespuestas().get(i)+"\n";

        }

        
        jTextArea1.setText(e);
        
    }//GEN-LAST:event_calcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular;
    private javax.swing.JButton ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField n;
    // End of variables declaration//GEN-END:variables

  
}
